# Generated by Django 5.2.8 on 2025-11-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=2000)),
                ('published_date', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
